### ISSUE TITLE
Cannot use energy dispersion with fermitools 

### ISSUE THREAD

**Issue by landriu** [fermi-lat/Fermitools-conda#52] opened 2019-10-11 13:25 UTC
Hello,

  I have tried to generate a binned like object using the nouveau argument edisp_bins, and 
got the following error message when calling BinnedAnalysis() : 
TypeError: __init__() got an unexpected keyword argument 'edisp_bins'

 What is the correct method to apply energy dispersion ? I could not get it in the documentation.

  The only occurence of string 'edisp_bins' being : 
[landriu@sappcfermi] ~ > grep edisp_bins /dsm/saplxglast/glast/fermitools/1.2.0/lib/python2.7/site-packages/fermitools/*py
/dsm/saplxglast/glast/fermitools/1.2.0/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py:                                   kwargs.get('edisp_bins', 0),
....

Thank you for your help, 
   David Landriu

PS: the whole test : 

[landriu@sappcfermi] ~ > python
Python 2.7.14 | packaged by conda-forge | (default, Oct  5 2017, 14:19:56) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
*** Using startup saving python history in ~/.pyhistory *** 

>>> from BinnedAnalysis import *

WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

>>> obs = BinnedObs( irfs="CALDB", expCube="ltCube_100.fits", srcMaps="srcMap_5_E1.fits", binnedExpMap="binned_exposure_E1.fits")
>>> like = BinnedAnalysis(obs,"srcModel_5_E1.xml-initial",optimizer="Minuit", edisp_bins=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'edisp_bins'
>>>

**Comment by donhorner** [comment] 2019-10-11 14:26
It looks like you are using the 1.2.0 version.  If you update, you should get the 1.2.1 version which fixed some issues with missing parameters.

**Comment by landriu** [comment] 2019-10-11 15:13
Sorry,

  I had the error in a fermitools 1.2.1 environment, but reproduced it in a 1.2.0 one .

I started again in  the proper one :

[landriu@sappcfermi] ~ > conda list | grep fermi
WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at /dsm/saplxglast/glast/fermitools/1.2.1:
ape                       2.9                           0    fermi
f2c                       0.0.1                         0    fermi
fermitools                1.2.1            py27h39e3cac_0    fermi
fermitools-data           0.17                          0    fermi

[landriu@sappcfermi] ~ > which python
/dsm/saplxglast/glast/fermitools/1.2.1/bin/python

[landriu@sappcfermi] ~ > which gtlike
/dsm/saplxglast/glast/fermitools/1.2.1/bin/fermitools/gtlike

[landriu@sappcfermi] ~ > python
Python 2.7.14 | packaged by conda-forge | (default, Oct  5 2017, 14:19:56) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
*** Using startup saving python history in ~/.pyhistory *** 

>>> from BinnedAnalysis import *

WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

>>> obs = BinnedObs( irfs="CALDB", expCube="ltCube_105.fits", srcMaps="srcMap_5_E4.fits", binnedExpMap="binned_exposure_E4.fits")

>>> like = BinnedAnalysis(obs,"srcModel_5_E4.xml-initial",optimizer="Minuit", edisp_bins=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'edisp_bins'
>>> 
>>> 

 My investigation tells me that the "grep   " command gives same result on  BinnedAnalysis.py : 

[landriu@sappcfermi] ~ > grep edisp_bins /dsm/saplxglast/glast/fermitools/1.2.1/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py
                                   kwargs.get('edisp_bins', 0),

   Only pyLikelihood.py has occurences of edisp_bins, but I do not know if there is a
relationship with the current problem.

Thank you again,

  David Landriu

 PS : 
[landriu@sappcfermi] ~ > grep edisp_bins /dsm/saplxglast/glast/fermitools/1.2.1/lib/python2.7/site-packages/fermitools/pyLikelihood.py
    def edisp_bins(self):
        """edisp_bins(BinnedLikeConfig self) -> size_t"""
        return _pyLikelihood.BinnedLikeConfig_edisp_bins(self)
        __init__(Likelihood::Drm self, double ra, double dec, Observation observation, DoubleVector ebounds, size_t edisp_bins=0) -> Drm
        __init__(Likelihood::Drm self, double ra, double dec, DoubleVector ebounds, DoubleVectorVector values, size_t edisp_bins=0) -> Drm
    def edisp_bins(self):
        """edisp_bins(Drm self) -> size_t"""
        return _pyLikelihood.Drm_edisp_bins(self)
def expand_energies(energies, edisp_bins):
    """expand_energies(DoubleVector energies, int edisp_bins)"""
    return _pyLikelihood.expand_energies(energies, edisp_bins)
    def edisp_bins(self):
        """edisp_bins(SourceMap self) -> size_t"""
        return _pyLikelihood.SourceMap_edisp_bins(self)

**Comment by donhorner** [comment] 2019-10-11 15:47
I can reproduce this.  We also had another problem report today about BinnedAnalysis, so maybe something didn't get implemented correctly there.  I'll have @jasercion take a look. He's out today and Monday is a holiday here, so he might not get to it until next week.

**Comment by jasercion** [comment] 2020-03-02 23:55
@landriu This should be fixed in the most recent release.  Can you please confirm if it is still present?

**Comment by dmalishev** [comment] 2020-03-24 18:02
Approach with edisp_bins definition via  BinnedConfig described  in
https://fermi.gsfc.nasa.gov/ssc/data/analysis/documentation/Pass8_edisp_usage.html
seems to work for **positive** values of edisp_bins.
Attempting to set edisp_bins to negative values, e.g. edisp_bins=-2 and checking if everything went fine:
conf = BinnedConfig(edisp_bins=-2)
print 'Conf edisp_bins = ' , conf.edisp_bins()
I've  got Conf edisp_bins = 0 , although no error, exception or warning is rised that 
conf = BinnedConfig(edisp_bins=-2) failed. 

For positive edisp_bins values correct value is returned by  conf.edisp_bins()

**Comment by donhorner** [comment] 2020-08-27 20:46
@landriu Is this still an issue or can it be closed?

**Comment by landriu** [comment] 2020-08-28 08:23
Hi Don,

  I have sent the following commands : 

from BinnedAnalysis import *
obs = BinnedObs( irfs="CALDB", expCube="ltCube_100.fits", srcMaps="srcMap_5_E1.fits",binnedExpMap="binned_exposure_E1.fits")
like = BinnedAnalysis(obs,"srcModel_5_E1.xml-initial",optimizer="Minuit", edisp_bins=0)
     
   and I still get the same outputs, with fermi-1.3.5 : 

(fermi-1.3.5) 
[landriu@sappcfermi] ~/dev/testEdisp_bins > python
Python 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:56:06) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
*** Using startup saving python history in ~/.pyhistory *** 

>>> from BinnedAnalysis import *
>>> obs = BinnedObs( irfs="CALDB", expCube="ltCube_100.fits", srcMaps="srcMap_5_E1.fits",binnedExpMap="binned_exposure_E1.fits")
>>> like = BinnedAnalysis(obs,"srcModel_5_E1.xml-initial",optimizer="Minuit", edisp_bins=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'edisp_bins'
>>> 
>>> 
(fermi-1.3.5)

**Comment by jasercion** [comment] 2020-08-31 19:46
@landriu To apply the weighed bins you need to create a `BinnedConfig` object and pass that object to `BinnedAnalysis`.  This should work:

`from BinnedAnalysis import *`
`conf = BinnedConfig(edisp_bins=0)`
`obs = BinnedObs( irfs="CALDB", expCube="ltCube_100.fits", srcMaps="srcMap_5_E1.fits",binnedExpMap="binned_exposure_E1.fits")`
`like = BinnedAnalysis(obs,"srcModel_5_E1.xml-initial",optimizer="Minuit", config=conf)`

**Comment by jasercion** [comment] 2020-08-31 19:47
Please let me know if you run into any other problems or if this works and we can close out the issue.

**Comment by jballet** [comment] 2020-09-02 08:27
Where is this documented? I have looked at the FSSC documentation, but [https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/binned_likelihood_tutorial.html](url) does not mention python, and [https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/python_tutorial.html](url) does not mention binned analysis, although [https://fermi.gsfc.nasa.gov/ssc/data/analysis/LAT_essentials.html](url) says binned analysis is most common and recommended.

**Comment by donhorner** [comment] 2020-09-02 14:38
It's on the page [https://fermi.gsfc.nasa.gov/ssc/data/analysis/documentation/Pass8_edisp_usage.html](https://fermi.gsfc.nasa.gov/ssc/data/analysis/documentation/Pass8_edisp_usage.html)

This page is linked to in some of the other pages, but I'll talk to Nestor about updating the documentation to make the information more obvious, especially on the python pages.

**Comment by jballet** [comment] 2020-09-02 15:27
OK, I see it. I think what is missing (or I could not find it) is a python tutorial for binned analysis, which would include this.

**Comment by jasercion** [comment] 2020-09-08 18:48
Issue verified fixed in both the python3 and python2 beta builds.  Closing issue and referring documentation updates to @donhorner and @nmirabal .

**Closed by jasercion** 2020-09-08 18:48 UTC
Labels: bug

**Comment by nmirabal** [comment] 2020-12-07 16:07
A tutorial on binned likelihood analysis with energy dispersion is now available at 
[](https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/binnededisp_tutorial.html)

**Comment by dmalishev** [comment] 2020-12-07 16:23
Thanks for putting this to the tutorial!

Just noticed, that gtexpcube2 also have (hidden) parameter edisp_bins:
https://raw.githubusercontent.com/fermi-lat/fermitools-fhelp/master/gtexpcube2.txt
should it be explicitly set to -2 as well? It is not set in the current tutorial.

Same for gtsrcmap step:
https://raw.githubusercontent.com/fermi-lat/fermitools-fhelp/master/gtsrcmaps.txt
should edisp_bins set to -2 too?

**Comment by jballet** [comment] 2020-12-07 16:59
The edisp_bins parameter is useful to gtexpcube2 and gtsrcmaps only if you want to set it positive in the fit (this requires having a spatial model beyond the energy interval used in the analysis). It can be ignored if you set edisp_bins to a negative value in the fit.
