### ISSUE TITLE
conda fermi : problem activating in tcsh

### ISSUE THREAD

**Issue by awstrong** [fermi-lat/Fermitools-conda#34] opened 2019-05-06 10:12 UTC
I installed latest fermitools with conda 4.6.14
I did
conda init tcsh
conda init bash
conda activate fermi             works under bash but not under tcsh

under tcsh, 'your shell has not been activated'  and    it just tells me to  conda init tcsh
which then returns 'no action' with a list of the shells scripts.
.tcshrc is modified but does not have the required effect, also when restarting tcsh

I also notice that conda init is 'Experimental' according to conda ---help

I can work with bash but it is not my standard shell.

**Comment by awstrong** [comment] 2019-05-06 10:19
NB I had previously used conda 4.2 for the init, before upgrading to 4.6
Perhaps the old init was erroneour, but how can I reset it? Edit .tcshrc by hand or is there a better way?

**Comment by donhorner** [comment] 2019-05-06 13:33
We’ve had another report of problems with csh, which I was able to reproduce. It looks like conda has broken the activation for (t)csh users in their most recent releases. It think you'll have to downgrade conda for now. 

The current version of conda is 4.6.14.  Based on the conda [release notes](https://github.com/conda/conda/blob/master/CHANGELOG.md), they have made various changes to the activation, especially for Windows, in the last few releases. I'm guessing they broke the csh activation in doing so.  Their support for tcsh/csh has always been problematic.

I managed to downgrade to 4.6.12 (downgrading to 4.6.13 failed) and the activation worked again.

We'll have to file a bug with the conda developers and add a note to our Troubleshooting page.  In the meantime, you can try downgrading conda:
* deactivate any conda environments
* run conda install conda=4.6.12
* Start a fresh shell or log back out and in again to make sure nothing lingers from before.
* Activate conda.

**Comment by awstrong** [comment] 2019-05-06 13:52
thanks, I may try that.
but if a bugfix is expected soon I can live with running under bash for 
now.

**Comment by donhorner** [comment] 2019-05-14 15:04
We have a beta release that should fix this issue.  It would be great if you could test it.  You can install the beta (we recommend creating a separate conda environment for testing) with the command:

conda create --name fermi_dev -c conda-forge/label/cf201901 -c fermi/label/beta -c fermi fermitools=1.0.5

Due to some metadata changes, it will probably also install fermitools-data and some other packages again. 

You can see full instructions on this page:
https://github.com/fermi-lat/Fermitools-conda/wiki/Testing-the-Fermitools

Let us know if it works.

**Comment by awstrong** [comment] 2019-05-14 16:12
OK thanks!
I don't quite understand: a new conda release which works for tcsh (if 
so what anaconda version is it) or a
new Fermitools which gets around the existing conda 4.6 tcsh problem?
Andrew

**Comment by donhorner** [comment] 2019-05-14 17:13
The second, a new Fermitools that includes a workaround.

**Comment by donhorner** [comment] 2019-05-14 20:06
This might not matter to your testing, but it looks like the beta was installing an old beta version of the fermitools-data package (0.15 vs. the current 0.17) that doesn't have the latest files, like the interstellar emission model.  That wouldn't have affected the activation but could have caused problems if you tried to do an analysis in the fermi_dev environment.  We've corrected that now.

**Comment by awstrong** [comment] 2019-05-15 05:48
thanks, I did not install it yet so will get the latest.

**Comment by jasercion** [comment] 2019-05-21 14:41
A fix for this has been included in the latest release of the Fermitools (Fermitools=1.0.5).

**Closed by jasercion** 2019-05-21 14:41 UTC
Labels: bug

**Comment by awstrong** [comment] 2019-05-21 15:51
thanks! so this is no longer beta (you mentioned before) but I can 
happily do
  conda updata fermi         ?

**Comment by donhorner** [comment] 2019-05-21 17:14
Yes, you should run: conda update -c conda-forge/label/cf201901 -c fermi fermitools

**Comment by awstrong** [comment] 2019-05-22 09:08
I did that, have 1.0.5
but it does not help

tcsh:

conda activate fermi

CommandNotFoundError: Your shell has not been properly configured to use 
'conda activate'.
To initialize your shell, run

     $ conda init <SHELL_NAME>

Currently supported shells are:
   - bash
   - fish
   - tcsh
   - xonsh
   - zsh
   - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 
'conda init'.


[aws@olga4 ~]$ conda init tcsh
no change     
/afs/ipp/.cs/anaconda/amd64_generic/3/2019.03/condabin/conda
no change     /afs/ipp/.cs/anaconda/amd64_generic/3/2019.03/bin/conda
no change     
/afs/ipp/.cs/anaconda/amd64_generic/3/2019.03/bin/conda-env
no change     /afs/ipp/.cs/anaconda/amd64_generic/3/2019.03/bin/activate
no change     
/afs/ipp/.cs/anaconda/amd64_generic/3/2019.03/bin/deactivate
no change     
/afs/ipp/.cs/anaconda/amd64_generic/3/2019.03/etc/profile.d/conda.sh
no change     
/afs/ipp/.cs/anaconda/amd64_generic/3/2019.03/etc/fish/conf.d/conda.fish
no change     
/afs/ipp/.cs/anaconda/amd64_generic/3/2019.03/shell/condabin/Conda.psm1
no change     
/afs/ipp/.cs/anaconda/amd64_generic/3/2019.03/shell/condabin/conda-hook.ps1
no change     
/afs/ipp/.cs/anaconda/amd64_generic/3/2019.03/lib/python3.7/site-packages/xonsh/conda.xsh
no change     
/afs/ipp/.cs/anaconda/amd64_generic/3/2019.03/etc/profile.d/conda.csh
no change     /afs/ipp-garching.mpg.de/home/a/aws/.tcshrc
No action taken.
[aws@olga4 ~]$ conda activate fermi

CommandNotFoundError: Your shell has not been properly configured to use 
'conda activate'.
To initialize your shell, run

     $ conda init <SHELL_NAME>

Currently supported shells are:
   - bash
   - fish
   - tcsh
   - xonsh
   - zsh
   - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 
'conda init'.

(Also after restarting shell). Do I perhaps have to cleanup .tcshrc  or 
something?

**Comment by awstrong** [comment] 2019-05-22 09:17
maybe I should do
conda init --reverse               ?

**Comment by donhorner** [comment] 2019-05-22 15:42
Instead of running "conda init", can you try just running:
`source </path/to/conda>/etc/profile.d/conda.csh`
where </path/to/conda> is replaced with the path to the top level directory of the Anaconda installation (typically named something like "Miniconda2") and then run `conda activate fermi`. You may want to comment out any of the conda stuff already in your .tcshrc and start with a clean shell.

**Comment by awstrong** [comment] 2019-05-24 08:17
thanks, but anaconda is provided by our computer center so making my own 
installation is not so nice, I can do it of course.

Is the workaround only valid for the conda.csh you mention below?
what is wrong with conda init --reverse  (I did not want to risk that 
yet though)

perhaps I should just wait till anaconda fixes the bug, since running 
under bash is not a big deal for the time being.
Andrew

**Comment by awstrong** [comment] 2019-05-24 10:51
I located conda.csh on the computer center installation. Will try it.

**Comment by awstrong** [comment] 2019-05-25 18:20
On 2019-05-24 12:51, aws wrote:
> I located conda.csh on the computer center installation. Will try it.
That worked. Thanks.
