### ISSUE TITLE
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

### ISSUE THREAD

**Issue by ShabnamIyyani** [fermi-lat/Fermitools-conda#112] opened 2021-09-13 07:46 UTC
Hi 
I have been trying to install the Fermi science tools using conda after my upgrade of MacOS to Big Sur.  I followed the command line that was given in the website. 

shabnam$ conda create --name fermi -c conda-forge -c fermi fermitools python=3 clhep=2.4.4.1
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 

The step of solving environment goes on endlessly. 

Please let me know how to resolve this.

**Comment by donhorner** [comment] 2021-09-13 18:53
Can you post the output of the 'uname -v' command?  Also, did the tools work before when the machine was Catalina?

We've had another installation problem report from a user with an x86 mac running Big Sur.  I'm wondering is the problem is limited to those type of machines. We haven't been able to  replicate the problem on a Catalina x86 mac and an M1 Big Sur mac.  We're trying to find an x86 mac running Big Sur to test with, but we don't have one immediately available.

**Comment by ShabnamIyyani** [comment] 2021-09-14 03:41
For the command 'uname -v', I get the following 
Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64

Earlier, I was using MacOS Mojave. I did not work in Catalina.

**Comment by BrunoArsioli** [comment] 2021-09-14 23:18
Hi @ShabnamIyyani, @jasercion, @donhorner. Do you think this is connected to #111?

**Comment by donhorner** [comment] 2021-09-16 15:18
@ShabnamIyyani Sorry, I didn't get back to you the other day.  Can you try installing and using the mamba installer as we suggest in the [troubleshooting suggestions](https://github.com/fermi-lat/Fermitools-conda/wiki/Troubleshooting#installation-issues)?   It's reimplementation of the conda package manager in C++ and is generally faster at resolving the dependencies.  It took ~10 minutes for conda to resolve on the x86 Big Sur machines I tested on, but mamba took ~1 minute. 

If that doesn't work, can you try doing the install using the dependency file I created from the Big Sur installation used for testing?  The file and instructions are given in the issue [#111](https://github.com/fermi-lat/Fermitools-conda/issues/111#issuecomment-920979859), which, as @BrunoArsioli suggests, may be related.

**Comment by ShabnamIyyani** [comment] 2021-09-17 11:13
@donhorner  Using mamba for installation did not work as the execution was taking a very long time and was not done. Later, I tried the second method that was suggested. The installation was done using the spec-file.txt. However, after activating fermi, when I tried to open gtburst, I got the following error

Traceback (most recent call last):
  File "/Users/shabnam/miniconda3/envs/fermi/lib/python3.7/site-packages/fermitools/gtburst.py", line 2091, in <module>
    g = GUI()
  File "/Users/shabnam/miniconda3/envs/fermi/lib/python3.7/site-packages/fermitools/gtburst.py", line 147, in handle_exception
    showerror("Unhandled exception", msg)
  File "/Users/shabnam/miniconda3/envs/fermi/lib/python3.7/tkinter/messagebox.py", line 91, in showerror
    return _show(title, message, ERROR, OK, **options)
  File "/Users/shabnam/miniconda3/envs/fermi/lib/python3.7/tkinter/messagebox.py", line 72, in _show
    res = Message(**options).show()
  File "/Users/shabnam/miniconda3/envs/fermi/lib/python3.7/tkinter/commondialog.py", line 39, in show
    w = Frame(self.master)
  File "/Users/shabnam/miniconda3/envs/fermi/lib/python3.7/tkinter/__init__.py", line 2744, in __init__
    Widget.__init__(self, master, 'frame', cnf, {}, extra)
  File "/Users/shabnam/miniconda3/envs/fermi/lib/python3.7/tkinter/__init__.py", line 2292, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/Users/shabnam/miniconda3/envs/fermi/lib/python3.7/tkinter/__init__.py", line 2259, in _setup
    _default_root = Tk()
  File "/Users/shabnam/miniconda3/envs/fermi/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /Users/birby/heasoft-6.28/heasoft-6.28/x86_64-apple-darwin18.7.0/lib/tcl8.6 /Users/shabnam/miniconda3/envs/fermi/lib/tcl8.6 /Users/shabnam/miniconda3/envs/lib/tcl8.6 /Users/shabnam/miniconda3/envs/fermi/library /Users/shabnam/miniconda3/envs/library /Users/shabnam/miniconda3/envs/tcl8.6.6/library /Users/shabnam/miniconda3/tcl8.6.6/library

/Users/shabnam/miniconda3/envs/fermi/lib/tcl8.6/init.tcl: version conflict for package "Tcl": have 8.6.6, need exactly 8.6.11
version conflict for package "Tcl": have 8.6.6, need exactly 8.6.11
    while executing
"package require -exact Tcl 8.6.11"
    (file "/Users/shabnam/miniconda3/envs/fermi/lib/tcl8.6/init.tcl" line 19)
    invoked from within
"source /Users/shabnam/miniconda3/envs/fermi/lib/tcl8.6/init.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list source $tclfile]"


This probably means that Tcl wasn't installed properly.


How should I resolve this?

**Comment by donhorner** [comment] 2021-09-17 14:44
I've seen this before, but I'm not sure why it occurs.  Maybe @jasercion has some insight?  However, you should be able to fix it by editing the file `/Users/shabnam/miniconda3/envs/fermi/lib/tcl8.6/init.tcl` and changing the line `package require -exact Tcl 8.6.11` to version 8.6.6.  You could also just comment out the line completely.  You'll also have to do the same with the file `/Users/shabnam/miniconda3/envs/fermi/lib/tk8.6/tk.tcl` or gtburst will throw a similar error.  After those changes, gtburst should start.

**Closed** 2022-01-03 04:04 UTC
