### ISSUE TITLE
Fermitools installation taking far too long 

### ISSUE THREAD

**Issue by BrunoArsioli** [fermi-lat/Fermitools-conda#111] opened 2021-09-10 02:13 UTC
Hi, I've tried to install fermitools in a MacOS 11.5.2, following instructions from [fermi-wiki](https://github.com/fermi-lat/Fermitools-conda/wiki/Installation-Instructions). I started by installing Miniconda (Miniconda3 MacOSX 64-bit pkg) and then, with zsh shell:

conda create -n fermi -c conda-forge -c fermi fermitools python=3 clhep=2.4.4.1

A series of packages were downloaded, and then I got the following messages:

"Preparing transaction: done
Verifying transaction: done
Executing transaction: /  "

The latest one "Executing transaction: " has been running for many hours . (> 10 h) 

I let it run that long, because I found many comments about users having similar problems with other packages (not fermitools) when trying to use "conda create -c conda-forge" . 

There are some [posts](https://github.com/jupyter/docker-stacks/issues/865) that talk about using "conda-metachannel" instead of conda-forge  , and also [here](https://www.anaconda.com/blog/understanding-and-improving-condas-performance). Is it safe to use conda-metachannel, trying to optimize the installation? 

(p.s. my   uname -a  :

Darwin MBP-de-xxx 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64  )

**Comment by donhorner** [comment] 2021-09-10 15:07
There certainly seems to be something wrong if it's taking that long.  You can look at the [troubleshooting suggestions](https://github.com/fermi-lat/Fermitools-conda/wiki/Troubleshooting#installation-issues), but I think the one that I would suggest is installing mamba, which is reimplementation of the conda package manager in C++ and is generally faster at resolving the dependencies. You can install it with the conda command `conda install mamba -c conda-forge` and then use it in place of the conda command (e.g., 'mamba install' instead of 'conda install').

I don't know anything about conda-metachannel.  Maybe @jasercion can comment on that.

**Comment by BrunoArsioli** [comment] 2021-09-10 23:02
I just installed mamba, and tried:

mamba create -n fermi -c conda-forge -c fermi fermitools python=3 clhep=2.4.4.1

I got :

WARNING: A conda environment already exists at '/Users/bs/opt/miniconda3/envs/fermi'
Remove existing environment (y/[n])? y

so, I removed envs/fermi (from the previous trial with conda create -n fermi ... )

The installation moved on, downloading some extra packages, 
and again, it went for many hours with this message: 

" Preparing transaction: done
Verifying transaction: done
Executing transaction: \  "

with the never ending  "Executing transaction"

**Comment by BrunoArsioli** [comment] 2021-09-11 15:59
After removing Miniconda and installing [Anaconda](https://www.anaconda.com/products/individual),  does not helped to solve the issue. After running for long time:

conda create -n fermi -c conda-forge -c fermi fermitools python=3 clhep=2.4.4.1

hitting ctrl+c some few times, showed this error message (before interrupting the process):
ERROR conda.core.link:_execute(699): An error occurred while installing package 'conda-forge::gdk-pixbuf-2.42.6-h2e6141f_0'.

(I am not sure if this helps. Is this related to where the process is stuck?)

**Comment by BrunoArsioli** [comment] 2021-09-14 22:46
Hi @donhorner , thank you for the attention. I tried that, but it didn't work. It is the same issue: never ending "Executing transaction: / " 

I also tried to update to MacOS BigSur 11.6, then:

conda update --all

conda update mamba

conda create -n fermi -c conda-forge -c fermi fermitools python=3 clhep=2.4.4.1

# or, for the dev version:

conda create -n fermi-2.0.24 -c conda-forge -c fermi/label/dev fermitools=2.0.24

# or: 

mamba create -n fermi -c conda-forge -c fermi fermitools python=3 clhep=2.4.4.1

All trials get stuck in " executing transaction \ " (> 1h) 

when hitting ctrl+c, all show the same error msg: 

# " ERROR conda.core.link:_execute(699): An error occurred while installing package 'conda-forge::gdk-pixbuf-2.42.6-h2e6141f_0'. " 
# " Rolling back transaction: done " 
 
my uname -v: 

Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64

**Comment by Areustle** [comment] 2021-09-16 14:59
Hi @BrunoArsioli . I am unsure what the cause of your conda/mamba install issue is, but since it seems to be related to your system's ability to resolve a suitable environment, @donhorner has generated an explicit one for you. I would like you to install this spec using the `--file` flag of `conda create`, which you can read about more by running `conda create --help`. Attached is a text file listing conda package URLs named [spec-file.txt](https://github.com/fermi-lat/Fermitools-conda/files/7178809/spec-file.txt). Please download this file to your system, then run `conda create -n fermi --file /path/to/spec-file.txt` (substituting /path/to/ appropriately). This should skip the environment resolution step. Afterwards you should be able `conda activate fermi` and proceed with using the fermitools.

The MD5 fingerprint for spec-file.txt is `9dbd3ba14cb8c7d13c2506a56e1ec1d5` which you can check on your mac by running `md5 /path/to/spec-file.txt`.

**Comment by BrunoArsioli** [comment] 2021-09-17 00:00
I just notice now that when I tried ``conda create -n fermi -c conda-forge -c fermi fermitools python=3 clhep=2.4.4.1`` , I get:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 

similar to #112 . 

after some minutes, it actually goes through the `Solving environment: -`  and then get stuck at  "Executing transaction: \" .  (for >1h )

**Comment by BrunoArsioli** [comment] 2021-09-17 00:01
Hi @Areustle, thank you for writing. I tried as you said (using ``conda create -n fermi --file xxxx/spec-file.txt``)  but the issue remains the same: Stuck at "Executing transaction: \" .  (for >1h )

When I hit ctrl+c, I get the same error msg as before:  

Executing transaction: - \ | - - done
ERROR conda.core.link:_execute(699): An error occurred while installing package 'conda-forge::gdk-pixbuf-2.42.6-h2e6141f_0'.
Rolling back transaction: done

**Comment by BrunoArsioli** [comment] 2021-09-17 00:16
Also, I tried to ``conda create -n foo -c conda-forge gdk-pixbuf=2.42.6=h2e6141f_0`` , then ``conda activate foo`` , and ``conda create -n fermi -c conda-forge -c fermi fermitools python=3 clhep=2.4.4.1`` ; I did that, trying to get through the gdk-pixbuf-2.42.6-h2e6141f_0  install.  But still, the process gets stuck at Executing transaction: - \ , and when I stop it with ctrl+c, the error is still the same: 

ERROR conda.core.link:_execute(699): An error occurred while installing package 'conda-forge::gdk-pixbuf-2.42.6-h2e6141f_0'.
Rolling back transaction: done

...

why conda is trying to install gdk-pixbuf-2.42.6-h2e6141f_0 , if it is already there? Is there a way to go through this step? (or, to remove this step, and install it separately?)

**Comment by BrunoArsioli** [comment] 2021-09-17 12:26
Trying something different:

now, created fermi env folder by hand:

``mkdir /opt/anaconda3/envs/fermi``

then, preinstall gdk-pixbuf-2.42.6-h2e6141f_0 pack (from conda-forge channel) at envs/fermi. 

``conda install gdk-pixbuf=2.42.6=h2e6141f_0 -c conda-forge -n fermi``

remove gdk-pixbuf-2.42.6-h2e6141f_0 from spec-file.txt

then, use install instead of create (since env/fermi is already there). 

``conda install -n fermi --file [path]/spec-file.txt``

the process get stuck, and after ctrl+c, got the following msg:
 
Executing transaction: / \ / \ / done
ERROR conda.core.link:_execute(699): An error occurred while installing package 'conda-forge::librsvg-2.50.7-hd2a7919_0'.
Rolling back transaction: | \ done

now, remove the env/fermi, start again from ``mkdir /opt/anaconda3/envs/fermi``

and this time, also pre-install two extra pack: 

``conda install gdk-pixbuf=2.42.6=h2e6141f_0 -c conda-forge -n fermi``

``conda install librsvg=2.50.7=hd2a7919_0 -c conda-forge -n fermi``

remove gdk-pixbuf-2.42.6-h2e6141f_0 and librsvg-2.50.7-hd2a7919_0 from spec-file.txt

and 

``conda install -n fermi --file [path]/spec-file.txt``

the process get stuck, and after ctrl+c, got the following msg:

Executing transaction: / - | done
ERROR conda.core.link:_execute(699): An error occurred while installing package 'conda-forge::graphviz-2.49.0-h77de9ca_0'.
Rolling back transaction: -


now, remove the envs/fermi, and try again

``mkdir /opt/anaconda3/envs/fermi``

and this time, pre-install three extra packs: 

``conda install gdk-pixbuf=2.42.6=h2e6141f_0 -c conda-forge -n fermi``

``conda install librsvg=2.50.7=hd2a7919_0 -c conda-forge -n fermi``

``conda install graphviz=2.49.0=h77de9ca_0 -c conda-forge -n fermi`` 

remove gdk-pixbuf-2.42.6-h2e6141f_0 and librsvg-2.50.7-hd2a7919_0 and graphviz=2.49.0=h77de9ca_0 from spec-file.txt

and 

``conda install -n fermi --file [path]/spec-file.txt``

now, the process get stuck, and after ctrl+c, there is NO error msg. 

....

Then, tried to install fermi-software with:

``conda install fermitools-dependencies=2.0.8-0 -c fermi -n fermi``

and 

``conda install fermitools=2.0.8=hb189bb9_0 -c fermi -n fermi``

in both cases there was similar msgs:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                       

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package expat conflicts for:
expat
graphviz==2.49.0=h77de9ca_0 -> expat[version='>=2.4.1,<3.0a0']
libgd -> expat[version='>=2.2.5,<3.0a0|>=2.2.6,<3.0a0|>=2.3.0,<3.0.0a0']
graphviz==2.49.0=h77de9ca_0 -> libgd[version='>=2.3.2,<2.4.0a0'] -> expat[version='>=2.3.0,<3.0.0a0']

Package gettext conflicts for:
atk-1.0 -> libglib[version='>=2.64.6,<3.0a0'] -> gettext[version='>=0.19.8.1,<1.0a0']
pango -> libglib[version='>=2.68.4,<3.0a0'] -> gettext[version='>=0.19.8.1,<1.0a0|>=0.21.0,<1.0a0']
gts -> glib[version='>=2.69.1,<3.0a0'] -> gettext[version='>=0.19.8.1,<1.0a0|>=0.21.0,<1.0a0']
atk-1.0 -> gettext[version='>=0.21.0,<1.0a0']
gtk2 -> atk-1.0[version='>=2.36.0'] -> gettext[version='>=0.21.0,<1.0a0']
gettext
harfbuzz -> libglib[version='>=2.68.4,<3.0a0'] -> gettext[version='>=0.19.8.1,<1.0a0|>=0.21.0,<1.0a0']
librsvg==2.50.7=hd2a7919_0 -> gdk-pixbuf[version='>=2.42.6,<3.0a0'] -> gettext[version='>=0.21.0,<1.0a0']
gdk-pixbuf==2.42.6=h2e6141f_0 -> libglib[version='>=2.68.0,<3.0a0'] -> gettext[version='>=0.19.8.1,<1.0a0']
cairo -> libglib[version='>=2.68.0,<3.0a0'] -> gettext[version='>=0.19.8.1,<1.0a0|>=0.21.0,<1.0a0']
librsvg==2.50.7=hd2a7919_0 -> gettext[version='>=0.19.8.1,<1.0a0']
libglib -> gettext[version='>=0.19.8.1,<1.0a0']
gtk2 -> gettext[version='>=0.19.8.1,<1.0a0']
graphviz==2.49.0=h77de9ca_0 -> gdk-pixbuf[version='>=2.42.6,<3.0a0'] -> gettext[version='>=0.19.8.1,<1.0a0|>=0.21.0,<1.0a0']

.
.
very long list with solving conflicts
.
.

and when I try ``conda activate fermi`` it shows no error message. 
But if I try to call a fermi routine like ``gtselect`` , I get 'zsh: command not found: gtselect'

**Comment by Areustle** [comment] 2021-09-17 15:30
That is concerning. It suggests you may have a deeper problem with your miniconda installation. The --file method doesn't (or isn't supposed to) do any environment solving.

I wonder if you're running out of storage on your mac? Or running out just in one critical partition? That might explain why the transactions can't complete, but it's total speculation. Check that by running `df -h`. Pay special attention to /opt or /tmp if they're partitioned separately. You can clean out your conda package cache with `conda clean --all`.

Barring that you're going to need to do a deep dive into the debug output of the `conda create` command. Remove the old fermi environment and run the command `conda create -n fermi --file .../spec-file.txt -vvv` command, but append `-vvv` to the invocation. Each 'v' will greatly increase the output of the program, 'v' is verbose, 'vv' is debug, and 'vvv' is trace. Going straight for `-vvv` will give you the most information. I suspect that when your output will either stop at some recognizable point (possibly related to gdk-pixbuf) or loop forever.

Please do not post the full output of that command here, as it may contain private system information that you do not want made public. But do let us know if it gives you any extra insight into this issue.

**Comment by BrunoArsioli** [comment] 2021-09-17 16:23
Hi @Areustle, thank you for writing. I will try to debug as you say. 
About the storage, there is still ~60Gb free in my disk. ``df -h`` shows:
Filesystem       Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1s5s1  466Gi   14Gi   32Gi    31%  553788 4882923132    0%   /
devfs           190Ki  190Ki    0Bi   100%     658          0  100%   /dev
/dev/disk1s4    466Gi  1.0Gi   32Gi     4%       2 4883476918    0%   /System/Volumes/VM
/dev/disk1s2    466Gi  357Mi   32Gi     2%    1532 4883475388    0%   /System/Volumes/Preboot
/dev/disk1s6    466Gi  2.8Mi   32Gi     1%      19 4883476901    0%   /System/Volumes/Update
/dev/disk1s1    466Gi  417Gi   32Gi    93% 1326714 4882150206    0%   /System/Volumes/Data
map auto_home     0Bi    0Bi    0Bi   100%       0          0  100%   /System/Volumes/Data/home

**Comment by BrunoArsioli** [comment] 2021-09-17 17:43
About the Miniconda installation, I've done the full Anaconda installation, and the issue remains the same.

**Comment by Areustle** [comment] 2021-09-22 18:20
Do you have any more information from your debug output @BrunoArsioli ?

**Comment by BrunoArsioli** [comment] 2021-09-22 21:12
Yes. I just clean conda cache ``sudo conda clean --all`` , and then removed conda completely with ``sudo rm -rf /op/anaconda3``following [uninstall-anaconda](https://docs.anaconda.com/anaconda/install/uninstall/); and removed conda initializer lines from my home ~./bash_profile. Rebot. Installed Anaconda full version for mac, from [here](https://docs.anaconda.com/anaconda/install/mac-os/). Installed anaconda3 in my home folder (full version Anaconda3-2021.05-MacOSX-x86_64.pkg) with no issues. Rebot. At this point, my storage shows 70 Gb of free space. Then, in terminal 

``conda create -n fermi -c conda-forge -c fermi fermitools python=3 clhep=2.4.4.1 -vvv`` , after some 20 min, it stops here:

.
.
TRACE conda.gateways.disk.permissions:make_executable(79): chmod +x /Users/xxxxx/opt/anaconda3/envs/fermi/bin/jupyter-bundlerextension
DEBUG conda.core.link:run_script(1203): for conda-forge::gdk-pixbuf-2.42.6-h2e6141f_0 at /Users/xxxxx/opt/anaconda3/envs/fermi, executing script: $ /bin/bash /Users/xxxxx/opt/anaconda3/envs/fermi/.tmp189snezu
DEBUG conda.gateways.subprocess:subprocess_call(71): executing>> /bin/bash /Users/xxxxx/opt/anaconda3/envs/fermi/.tmp189snezu

The same issue as I reported before, stuck at conda-forge::gdk-pixbuf-2.42.6-h2e6141f_0  ....  then, ctrl+c, stops at:
.
.
TRACE conda.core.path_actions:reverse(381): reversing link creation /Users/xxxxx/opt/anaconda3/envs/fermi
DEBUG conda.core.link:run_script(1203): for conda-forge::librsvg-2.50.7-hd2a7919_0 at /Users/xxxxx/opt/anaconda3/envs/fermi, executing script: $ /bin/bash /Users/xxxxx/opt/anaconda3/envs/fermi/.tmpiqfd9sbg
DEBUG conda.gateways.subprocess:subprocess_call(71): executing>> /bin/bash /Users/xxxxx/opt/anaconda3/envs/fermi/.tmpiqfd9sbg

The same issue as I reported before with conda-forge::librsvg-2.50.7-hd2a7919_0 , then, ctrl+c, stops at:
.
.
TRACE conda.core.path_actions:reverse(381): reversing link creation /Users/xxxxx/opt/anaconda3/envs/fermi
DEBUG conda.core.link:run_script(1203): for conda-forge::graphviz-2.49.0-h77de9ca_0 at /Users/xxxxx/opt/anaconda3/envs/fermi, executing script: $ /bin/bash /Users/xxxxx/opt/anaconda3/envs/fermi/.tmpz4vp9dlw
DEBUG conda.gateways.subprocess:subprocess_call(71): executing>> /bin/bash /Users/xxxxx/opt/anaconda3/envs/fermi/.tmpz4vp9dlw

The same issue as I reported before with conda-forge::graphviz-2.49.0-h77de9ca_0 , then, ctrl+c, stops at: 
.
.
" TRACE conda.core.path_actions:execute(562): compiling ....[very long list of file paths] 
TRACE conda.gateways.disk.create:compile_multiple_pyc(399): ['/Users/xxxxx/opt/anaconda3/envs/fermi/bin/python3.7', '-Wi', '-m', 'compileall', '-q', '-l', '-i', '/var/folders/2_/1jjw_1g13w7gxhcwr71wk1jh0000gn/T/tmpymc4lv3w', '-j', '0']

then, if I hit ctrl+c again, it is over, with:
.
.
conda.CondaMultiError: Signal interrupt SIGINT
()

**Comment by BrunoArsioli** [comment] 2021-09-22 21:27
Then, another trial: I clean the cache ``sudo conda clean --all``, and remove fermi env ``rm -rf /Users/xxxxx/opt/anaconda3/envs/fermi``. Rebot. One of the messages I saw through the -vvv comments was a suggestion to update conda using ``conda update -n base -c defaults conda`` , so, I just did that now. Implementing the following: conda  4.10.1-py38hecd8cb5_1 --> 4.10.3-py38hecd8cb5_0   and   xmltodict   0.12.0-py_0 --> 0.12.0-pyhd3eb1b0_0 .  Then ``conda create -n fermi --file [path]/spec-file.txt -vvv`` 

Again, the process stops at conda-forge::gdk-pixbuf-2.42.6-h2e6141f_0 ; same msg, then stops at: conda-forge::librsvg-2.50.7-hd2a7919_0 , and again at conda-forge::graphviz-2.49.0-h77de9ca_0 . Then, it stops again at " TRACE conda.gateways.disk.create:compile_multiple_pyc(399): ['/Users/xxxxx/opt/anaconda3/envs/fermi/bin/python3.7', '-Wi', '-m', 'compileall', '-q', '-l', '-i', '/var/folders/2_/1jjw_1g13w7gxhcwr71wk1jh0000gn/T/tmpiwml47bn', '-j', '0'] "  , and after ctrol+c , it is over. just as in previous trials.

**Comment by BrunoArsioli** [comment] 2022-01-23 05:45
Found a fix. Now with Mac Bigsur 11.6.2 

First, I downgraded Xcode to 13.0 , following #116

Then, reading: 
[link1](https://exerror.com/solving-environment-failed-with-initial-frozen-solve-retrying-with-flexible-solve/)

[link2](https://programmerah.com/solve-condas-solving-environment-failed-problem-4018/)

[link3-check comment from "glass-ships"](https://github.com/conda/conda/issues/9004)

[link4](https://dizzycoding.com/solving-environment-failed-with-repodata-from-current_repodata-json-will-retry-with-next-repodata-source-code-answer/)

I tried:

``conda update conda -c conda-canary``

``conda config --set channel_priority false``
 
( if there is already a xxx/env/fermi , remove with rm -r xxx/env/fermi )

``conda create --name fermi`` 

``conda activate fermi``

``conda install -c fermi fermitools python=3 clhep=2.4.4.1`` 

then:  ``conda activate fermi`` and the fermitools seems to be working now.

**Comment by kerrm** [comment] 2022-01-23 16:41
Wow, nice detective work!

**Comment by donhorner** [comment] 2022-05-23 20:40
We have a development version of the Fermitools that we hope to release soon that should fix most installation problems because we removed the ROOT package, which was the source of many of these issues. If you like to test it, you can install the dev version with the command:
`conda create -n fermitools-2.1.30 -c conda-forge -c fermi/label/dev fermitools=2.1.30`

**Comment by donhorner** [comment] 2022-06-22 15:36
Fermitools 2.2.0 has been released which fixes this issue.

**Closed by donhorner** 2022-06-22 15:36 UTC
